# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

os: Visual Studio 2015

init:
  - git config --global core.autocrlf input

cache:
  - C:\Users\appveyor\.node-gyp
  - '%AppData%\npm-cache'

matrix:
  fast_finish: true

# what combinations to test
environment:
  matrix:
    - nodejs_version: 6

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host x86_64-pc-windows-msvc --default-toolchain stable
  - set PATH=%PATH%;%HOMEPATH%\.cargo\bin
  - ps: Install-Product node $env:nodejs_version x64
  - npm install -g npm@4
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - cmd: npm test

deploy_script:
  - IF "%APPVEYOR_REPO_TAG%" == "true" (npm run release)
  - IF NOT "%APPVEYOR_REPO_TAG%" == "true" (echo 'Not tagged, skipping deploy')
